# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-03 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('created_by', models.CharField(blank=True, max_length=32, verbose_name='创建者')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '节点分组',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('is_active', models.BooleanField(default=False, verbose_name='状态')),
                ('check_time', models.DateTimeField(blank=True, verbose_name='检测时间')),
                ('node_url', models.CharField(max_length=128, unique=True, verbose_name='节点URL')),
                ('ip', models.CharField(blank=True, max_length=32, verbose_name='IP')),
                ('admin_users', models.TextField(blank=True, verbose_name='授权用户')),
                ('hostname', models.CharField(blank=True, max_length=128, verbose_name='主机名')),
                ('server_version', models.CharField(blank=True, max_length=32, verbose_name='Docker版本')),
                ('container_total', models.IntegerField(default=0, verbose_name='容器总数')),
                ('container_running', models.IntegerField(default=0, verbose_name='容器运行数')),
                ('container_paused', models.IntegerField(default=0, verbose_name='容器暂停数')),
                ('container_stopped', models.IntegerField(default=0, verbose_name='容器停止数')),
                ('images', models.IntegerField(default=0, verbose_name='镜像总数')),
                ('cpu_count', models.IntegerField(blank=True, default=0, verbose_name='CPU核心')),
                ('memory', models.CharField(blank=True, max_length=128, verbose_name='内存总量')),
                ('os', models.CharField(blank=True, max_length=128, verbose_name='操作系统')),
                ('os_arch', models.CharField(blank=True, max_length=16, verbose_name='系统架构')),
                ('created_by', models.CharField(blank=True, max_length=32, verbose_name='创建者')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_nodes', to='hosts.HostGroup', verbose_name='主机分组')),
            ],
            options={
                'verbose_name': '宿主节点',
                'ordering': ['name'],
            },
        ),
    ]
