# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-03 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostnode',
            name='container_paused',
            field=models.IntegerField(blank=True, default=0, verbose_name='容器暂停数'),
        ),
        migrations.AlterField(
            model_name='hostnode',
            name='container_running',
            field=models.IntegerField(blank=True, default=0, verbose_name='容器运行数'),
        ),
        migrations.AlterField(
            model_name='hostnode',
            name='container_stopped',
            field=models.IntegerField(blank=True, default=0, verbose_name='容器停止数'),
        ),
        migrations.AlterField(
            model_name='hostnode',
            name='container_total',
            field=models.IntegerField(blank=True, default=0, verbose_name='容器总数'),
        ),
        migrations.AlterField(
            model_name='hostnode',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_nodes', to='hosts.HostGroup', verbose_name='主机分组'),
        ),
        migrations.AlterField(
            model_name='hostnode',
            name='images',
            field=models.IntegerField(blank=True, default=0, verbose_name='镜像总数'),
        ),
    ]
