# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-14 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='主机ID')),
                ('node_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名称')),
            ],
            options={
                'verbose_name': '当前主机',
            },
        ),
    ]
