# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-05 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostgroup',
            options={'ordering': ['name'], 'verbose_name': '主机组'},
        ),
        migrations.AlterModelOptions(
            name='hostnode',
            options={'ordering': ['name'], 'verbose_name': '主机'},
        ),
        migrations.AddField(
            model_name='hostnode',
            name='c_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='容器数'),
        ),
        migrations.AddField(
            model_name='hostnode',
            name='i_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='镜像数'),
        ),
    ]
