# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-14 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_currnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='currnode',
            name='node_url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='主机URL'),
        ),
    ]
