# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-03 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20190703_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostnode',
            name='check_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='检测时间'),
        ),
    ]
