# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-03 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_auto_20190703_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostnode',
            name='check_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='检测时间'),
        ),
        migrations.AlterField(
            model_name='hostnode',
            name='is_active',
            field=models.BooleanField(verbose_name='状态'),
        ),
    ]
