# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-03 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_auto_20190703_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostnode',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='状态'),
        ),
    ]
