# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-05 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_auto_20190705_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostnode',
            name='check_time',
            field=models.DateTimeField(auto_now=True, verbose_name='检测时间'),
        ),
    ]
