# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-15 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=64, verbose_name='用户')),
                ('type', models.CharField(blank=True, max_length=64, verbose_name='分类')),
                ('action', models.CharField(blank=True, max_length=64, verbose_name='动作')),
                ('state', models.BooleanField(default=False, verbose_name='状态')),
                ('content', models.CharField(blank=True, max_length=512, verbose_name='内容')),
                ('time_ops', models.DateTimeField(auto_now=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '系统日志',
            },
        ),
    ]
