# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-12 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syslogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='state',
            field=models.BooleanField(default=False, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='log',
            name='content',
            field=models.CharField(blank=True, max_length=256, verbose_name='内容'),
        ),
    ]
